/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employermanagment;

import static employermanagment.EmployeePanel.jTable1;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;

/**
 *
 * @author user
 */
public class AddDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddDialog
     */
    public AddDialog() {

    }

    public AddDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Add Employee");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        spnBirthDate =  new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        cmbDepartment = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        chkSingle = new javax.swing.JCheckBox();
        chkMarrid = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID number :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(15, 19, 100, 20);

        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(15, 54, 52, 20);

        jLabel3.setText("Birth Date :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(15, 98, 81, 20);

        jLabel4.setText("Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(15, 334, 68, 20);

        jLabel5.setText("Department :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(15, 142, 94, 20);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(130, 10, 80, 26);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(130, 50, 80, 26);

        SimpleDateFormat model = new SimpleDateFormat("dd.MM.yy");
        spnBirthdate = new JSpinner(new SpinnerDateModel());
        spnBirthdate.setEditor(new JSpinner.DateEditor(spnBirthdate, model.toPattern()));

        getContentPane().add(spnBirthdate);
        spnBirthdate.setBounds(130, 100, 130, 24);
        getContentPane().add(spnBirthDate);
        spnBirthDate.setBounds(130, 100, 130, 26);
        spnBirthDate.setVisible(false);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 330, 182, 75);

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Manegment", "Sales" }));
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDepartment);
        cmbDepartment.setBounds(127, 139, 140, 26);

        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(15, 202, 62, 20);

        jLabel7.setText("Status :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(15, 266, 54, 20);

        buttonGroup1.add(rbtnMale);
        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnMale);
        rbtnMale.setBounds(120, 200, 65, 29);

        buttonGroup1.add(rbtnFemale);
        rbtnFemale.setText("Female");
        getContentPane().add(rbtnFemale);
        rbtnFemale.setBounds(262, 198, 83, 29);

        buttonGroup2.add(chkSingle);
        chkSingle.setText("Single");
        getContentPane().add(chkSingle);
        chkSingle.setBounds(120, 260, 75, 29);

        buttonGroup2.add(chkMarrid);
        chkMarrid.setText("Married ");
        getContentPane().add(chkMarrid);
        chkMarrid.setBounds(262, 262, 91, 29);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(240, 450, 65, 29);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 450, 79, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File("allUsersObject.txt");
            list = read(file);

            if (txtName.getText().equals("") || txtId.getText().equals("") || cmbDepartment.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(this, "please enter all requird field...!");

            } else if (checkId()) {
            } else {

                User newUser = new User();
                newUser.setId(Integer.valueOf(txtId.getText()));
                newUser.setName(txtName.getText());
                newUser.setAddress(txtAddress.getText());
                newUser.setDepartment(cmbDepartment.getSelectedItem().toString());
                newUser.setBarthDate(new SimpleDateFormat("yyyy/MM/dd").format(spnBirthdate.getValue()));
                newUser.setGender((rbtnMale.isSelected()) ? "Male" : "Female");
                newUser.setStatus((chkSingle.isSelected()) ? "Single" : "Marrid");
//            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

                write(file, newUser);

                for (User oneUser : list) {
                    System.out.println(oneUser);
//                    tableModel.addRow(userData);
                }

                JOptionPane.showMessageDialog(this, "Add Successfully");
                dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Please enter a number");
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void write(File file, User user) throws Exception {
        FileOutputStream fileOut = new FileOutputStream(file, true);

        if (file.length() < 1) {
            ObjectOutputStream oos = new ObjectOutputStream(fileOut);
            oos.writeObject(user);
            oos.close();
        } else {
            MyObjectOutputStream mos = new MyObjectOutputStream(fileOut);
            mos.writeObject(user);
            mos.close();
        }
    }

    //Deserialization
    public static  List<User> read(File file) throws Exception {
        List<User> list = new ArrayList<User>();
        FileInputStream fis = new FileInputStream(file);
        try (ObjectInputStream ois = new ObjectInputStream(fis)) {
            while (fis.available() > 0) {
                User p = (User) ois.readObject();
                list.add(p);
            }
        }
        return list;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDialog dialog = new AddDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean checkId() {

        boolean flag = false;
        for (User oneUser : list) {
            if (Long.valueOf(txtId.getText()).equals(oneUser.getId())) {
                JOptionPane.showMessageDialog(this, "Id number is alredy exist");
                flag = true;
                break;
            }
        }
        return flag;
    }

    private JSpinner spnBirthdate;
    public List<User> list;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkMarrid;
    private javax.swing.JCheckBox chkSingle;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JSpinner spnBirthDate;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
