/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employermanagment;

import static employermanagment.EmployeePanel.updatedUser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author user
 */
public class UpdateDialog extends javax.swing.JDialog {

    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    /**
     * Creates new form UpdateDialog
     */
    public UpdateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtName.setText(updatedUser.getName());
        txtAddress.setText(updatedUser.getAddress());
        cmbDepartment.setSelectedItem(updatedUser.getDepartment());
        
        if (updatedUser.getGender().equals("Male")) {
            rbtnMale.setSelected(true);
        } else {
            rbtnFemale.setSelected(true);
        }

        if (updatedUser.getStatus().equals("Single")) {
            chkSingle.setSelected(true);
        } else {
            chkMarrid.setSelected(true);

        }
    }

    UpdateDialog() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        spnBirthDate = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        cmbDepartment = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        chkSingle = new javax.swing.JCheckBox();
        chkMarrid = new javax.swing.JCheckBox();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 52, 20);

        jLabel3.setText("Birth Date :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 81, 20);

        jLabel4.setText("Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 300, 68, 20);

        jLabel5.setText("Department :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 94, 20);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(140, 20, 80, 26);

        SimpleDateFormat model = new SimpleDateFormat("dd.MM.yy");
        spnBirthdate = new JSpinner(new SpinnerDateModel());
        spnBirthdate.setEditor(new JSpinner.DateEditor(spnBirthdate, model.toPattern()));

        getContentPane().add(spnBirthdate);
        spnBirthdate.setBounds(140, 70, 130, 26);
        getContentPane().add(spnBirthDate);
        spnBirthDate.setBounds(140, 70, 130, 26);
        spnBirthDate.setVisible(false);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 300, 182, 75);

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Manegment", "Sales" }));
        getContentPane().add(cmbDepartment);
        cmbDepartment.setBounds(140, 110, 130, 26);

        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 62, 20);

        jLabel7.setText("Status :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 230, 54, 20);

        rbtnMale.setText("Male");
        getContentPane().add(rbtnMale);
        rbtnMale.setBounds(130, 170, 65, 29);

        rbtnFemale.setText("Female");
        getContentPane().add(rbtnFemale);
        rbtnFemale.setBounds(270, 170, 83, 29);

        chkSingle.setText("Single");
        getContentPane().add(chkSingle);
        chkSingle.setBounds(130, 230, 75, 29);

        chkMarrid.setText("Married ");
        getContentPane().add(chkMarrid);
        chkMarrid.setBounds(270, 230, 91, 29);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(250, 420, 80, 29);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(350, 420, 79, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // TODO add your handling code here:

            File file = new File("allUsersObject.txt");

            User newUpdatedUser = new User();
            newUpdatedUser.setId(updatedUser.getId());
            newUpdatedUser.setName(txtName.getText());
            newUpdatedUser.setAddress(txtAddress.getText());
            newUpdatedUser.setDepartment(cmbDepartment.getSelectedItem().toString());
            newUpdatedUser.setBarthDate(new SimpleDateFormat("yyyy/MM/dd").format(spnBirthdate.getValue()));
            newUpdatedUser.setGender((rbtnMale.isSelected()) ? "Male" : "Female");
            newUpdatedUser.setStatus((chkSingle.isSelected()) ? "Single" : "Marrid");

            update(file, newUpdatedUser);
        } catch (Exception ex) {
            Logger.getLogger(UpdateDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateDialog dialog = new UpdateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public  void update(File file, User user) throws Exception {


        list = read(file);

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getId() == (updatedUser.getId())) {
                list.remove(i);
                list.add(user);
                
                System.out.println("user updated");
                JOptionPane.showMessageDialog(this, "Add Successfully");
                dispose();
                break;
            }

        }
        FileOutputStream fileOut = new FileOutputStream(file);

        ObjectOutputStream oos = new ObjectOutputStream(fileOut);
        for (User oneUser : list) {
            oos.writeObject(oneUser);

        }
        oos.close();

    }
    
    
    public static  List<User> read(File file) throws Exception {
        List<User> list = new ArrayList<User>();
        FileInputStream fis = new FileInputStream(file);
        try (ObjectInputStream ois = new ObjectInputStream(fis)) {
            while (fis.available() > 0) {
                User p = (User) ois.readObject();
                list.add(p);
            }
        }
        return list;
    }
    private JSpinner spnBirthdate;
    List<User> list;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkMarrid;
    private javax.swing.JCheckBox chkSingle;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JSpinner spnBirthDate;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
